use_frameworks!

platform :ios, '11.0'

target 'SHPlayer_Example' do
  pod 'SHPlayer', :path => '../'

  target 'SHPlayer_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    config.build_settings['CODE_SIGN_IDENTITY'] = ''
  end
end
